[package]
name = "easycontainer_lib"
version = "0.1.0"
authors = ["timglabisch <tim@ainfach.de>"]
edition = "2021"

[dependencies]
tokio = { version = "1.*", features = ["full"] }
anyhow = "1.0.*"
tracing = "0.1.*"
futures = "0.3.*"
serde = "1.*"
serde_derive = "1.*"
toml = "0.*"
glob = "0.*"